// Procedural sound system using Web Audio API
// No external files needed — all sounds synthesized

// Royal Road progression in A minor — generated by python/generate_music.py
// Progression: Fmaj7 → G7 → Em7 → Am

const CHORD_FREQS = [
  /* Fmaj7 */ [349.23, 440.00, 523.25, 659.25],
  /* G7    */ [392.00, 493.88, 587.33, 698.46],
  /* Em7   */ [329.63, 392.00, 493.88, 587.33],
  /* Am    */ [220.00, 261.63, 329.63, 440.00],
];

const MELODY_FREQS = [
  /* Fmaj7 */ [349.23, 440.00, 523.25, 659.25, 523.25, 440.00],
  /* G7    */ [392.00, 493.88, 587.33, 698.46, 587.33, 493.88],
  /* Em7   */ [329.63, 392.00, 493.88, 587.33, 493.88, 392.00],
  /* Am    */ [220.00, 261.63, 329.63, 440.00, 329.63, 261.63],
];

const BASS_FREQS = [
  /* Fmaj7 */ 174.61,
  /* G7    */ 196.00,
  /* Em7   */ 164.81,
  /* Am    */ 110.00,
];

const CHORD_DURATION = 2.5;
const MELODY_NOTE_DURATION = 0.35;
const TOTAL_PROGRESSION_TIME = 10.0;

// ============ Audio context ============

let audioCtx = null

function getCtx() {
  if (!audioCtx) {
    audioCtx = new (window.AudioContext || window.webkitAudioContext)()
  }
  if (audioCtx.state === 'suspended') audioCtx.resume()
  return audioCtx
}

// ============ SFX ============

export function playFootstep() {
  try {
    const ctx = getCtx()
    const osc = ctx.createOscillator()
    const gain = ctx.createGain()
    // Low-pass filter for muffled stone step
    const filter = ctx.createBiquadFilter()
    filter.type = 'lowpass'
    filter.frequency.value = 400 + Math.random() * 200
    osc.connect(filter)
    filter.connect(gain)
    gain.connect(ctx.destination)
    osc.type = 'triangle'
    osc.frequency.setValueAtTime(60 + Math.random() * 40, ctx.currentTime)
    gain.gain.setValueAtTime(0.04, ctx.currentTime)
    gain.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + 0.1)
    osc.start(ctx.currentTime)
    osc.stop(ctx.currentTime + 0.1)
  } catch (e) { /* audio not available */ }
}

export function playCrystalCollect() {
  try {
    const ctx = getCtx()
    // Main chime
    const osc = ctx.createOscillator()
    const gain = ctx.createGain()
    osc.connect(gain)
    gain.connect(ctx.destination)
    osc.type = 'sine'
    osc.frequency.setValueAtTime(880, ctx.currentTime)
    osc.frequency.exponentialRampToValueAtTime(1760, ctx.currentTime + 0.15)
    gain.gain.setValueAtTime(0.12, ctx.currentTime)
    gain.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + 0.3)
    osc.start(ctx.currentTime)
    osc.stop(ctx.currentTime + 0.3)
    // Sparkle overtone
    const osc2 = ctx.createOscillator()
    const gain2 = ctx.createGain()
    osc2.connect(gain2)
    gain2.connect(ctx.destination)
    osc2.type = 'sine'
    osc2.frequency.setValueAtTime(1320, ctx.currentTime + 0.05)
    osc2.frequency.exponentialRampToValueAtTime(2640, ctx.currentTime + 0.2)
    gain2.gain.setValueAtTime(0.06, ctx.currentTime + 0.05)
    gain2.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + 0.25)
    osc2.start(ctx.currentTime + 0.05)
    osc2.stop(ctx.currentTime + 0.25)
  } catch (e) {}
}

export function playPortalActivate() {
  try {
    const ctx = getCtx()
    const osc = ctx.createOscillator()
    const gain = ctx.createGain()
    osc.connect(gain)
    gain.connect(ctx.destination)
    osc.type = 'triangle'
    osc.frequency.setValueAtTime(440, ctx.currentTime)
    osc.frequency.exponentialRampToValueAtTime(880, ctx.currentTime + 0.5)
    osc.frequency.exponentialRampToValueAtTime(1320, ctx.currentTime + 1.0)
    gain.gain.setValueAtTime(0.1, ctx.currentTime)
    gain.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + 1.2)
    osc.start(ctx.currentTime)
    osc.stop(ctx.currentTime + 1.2)
    // Hum layer
    const osc2 = ctx.createOscillator()
    const gain2 = ctx.createGain()
    osc2.connect(gain2)
    gain2.connect(ctx.destination)
    osc2.type = 'sine'
    osc2.frequency.setValueAtTime(220, ctx.currentTime)
    osc2.frequency.exponentialRampToValueAtTime(440, ctx.currentTime + 1.0)
    gain2.gain.setValueAtTime(0.05, ctx.currentTime)
    gain2.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + 1.2)
    osc2.start(ctx.currentTime)
    osc2.stop(ctx.currentTime + 1.2)
  } catch (e) {}
}

export function playDeath() {
  try {
    const ctx = getCtx()
    const osc = ctx.createOscillator()
    const gain = ctx.createGain()
    const osc2 = ctx.createOscillator()
    const gain2 = ctx.createGain()

    osc.connect(gain)
    gain.connect(ctx.destination)
    osc.type = 'sawtooth'
    osc.frequency.setValueAtTime(200, ctx.currentTime)
    osc.frequency.exponentialRampToValueAtTime(40, ctx.currentTime + 1.5)
    gain.gain.setValueAtTime(0.08, ctx.currentTime)
    gain.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + 1.8)

    osc2.connect(gain2)
    gain2.connect(ctx.destination)
    osc2.type = 'square'
    osc2.frequency.setValueAtTime(100, ctx.currentTime)
    osc2.frequency.exponentialRampToValueAtTime(20, ctx.currentTime + 1.5)
    gain2.gain.setValueAtTime(0.04, ctx.currentTime)
    gain2.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + 1.8)

    osc.start(ctx.currentTime)
    osc.stop(ctx.currentTime + 1.8)
    osc2.start(ctx.currentTime)
    osc2.stop(ctx.currentTime + 1.8)
  } catch (e) {}
}

export function playKeyCollect() {
  try {
    const ctx = getCtx()
    // Rising triplet
    const osc = ctx.createOscillator()
    const gain = ctx.createGain()
    osc.connect(gain)
    gain.connect(ctx.destination)
    osc.type = 'triangle'
    osc.frequency.setValueAtTime(660, ctx.currentTime)
    osc.frequency.setValueAtTime(880, ctx.currentTime + 0.1)
    osc.frequency.setValueAtTime(1100, ctx.currentTime + 0.2)
    gain.gain.setValueAtTime(0.1, ctx.currentTime)
    gain.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + 0.35)
    osc.start(ctx.currentTime)
    osc.stop(ctx.currentTime + 0.35)
    // Metallic ring
    const osc2 = ctx.createOscillator()
    const gain2 = ctx.createGain()
    osc2.connect(gain2)
    gain2.connect(ctx.destination)
    osc2.type = 'sine'
    osc2.frequency.setValueAtTime(2200, ctx.currentTime + 0.15)
    osc2.frequency.exponentialRampToValueAtTime(1800, ctx.currentTime + 0.4)
    gain2.gain.setValueAtTime(0.05, ctx.currentTime + 0.15)
    gain2.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + 0.45)
    osc2.start(ctx.currentTime + 0.15)
    osc2.stop(ctx.currentTime + 0.45)
  } catch (e) {}
}

export function playDoorOpen() {
  try {
    const ctx = getCtx()
    // Rumble + grind
    const osc = ctx.createOscillator()
    const gain = ctx.createGain()
    const filter = ctx.createBiquadFilter()
    filter.type = 'lowpass'
    filter.frequency.setValueAtTime(300, ctx.currentTime)
    filter.frequency.exponentialRampToValueAtTime(60, ctx.currentTime + 0.6)
    osc.connect(filter)
    filter.connect(gain)
    gain.connect(ctx.destination)
    osc.type = 'square'
    osc.frequency.setValueAtTime(180, ctx.currentTime)
    osc.frequency.exponentialRampToValueAtTime(60, ctx.currentTime + 0.6)
    gain.gain.setValueAtTime(0.08, ctx.currentTime)
    gain.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + 0.7)
    osc.start(ctx.currentTime)
    osc.stop(ctx.currentTime + 0.7)
    // Stone scrape overtone
    const osc2 = ctx.createOscillator()
    const gain2 = ctx.createGain()
    osc2.connect(gain2)
    gain2.connect(ctx.destination)
    osc2.type = 'sawtooth'
    osc2.frequency.setValueAtTime(80, ctx.currentTime)
    osc2.frequency.exponentialRampToValueAtTime(40, ctx.currentTime + 0.5)
    gain2.gain.setValueAtTime(0.03, ctx.currentTime)
    gain2.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + 0.6)
    osc2.start(ctx.currentTime)
    osc2.stop(ctx.currentTime + 0.6)
  } catch (e) {}
}

export function playSpikeHurt() {
  try {
    const ctx = getCtx()
    // Metallic sting — sharp and painful
    const osc = ctx.createOscillator()
    const gain = ctx.createGain()
    const filter = ctx.createBiquadFilter()
    filter.type = 'bandpass'
    filter.frequency.value = 3000
    filter.Q.value = 5
    osc.connect(filter)
    filter.connect(gain)
    gain.connect(ctx.destination)
    osc.type = 'square'
    osc.frequency.setValueAtTime(1200, ctx.currentTime)
    osc.frequency.exponentialRampToValueAtTime(400, ctx.currentTime + 0.15)
    gain.gain.setValueAtTime(0.1, ctx.currentTime)
    gain.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + 0.2)
    osc.start(ctx.currentTime)
    osc.stop(ctx.currentTime + 0.2)
    // Sub-harmonic thud
    const osc2 = ctx.createOscillator()
    const gain2 = ctx.createGain()
    osc2.connect(gain2)
    gain2.connect(ctx.destination)
    osc2.type = 'sine'
    osc2.frequency.setValueAtTime(55, ctx.currentTime)
    gain2.gain.setValueAtTime(0.06, ctx.currentTime)
    gain2.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + 0.12)
    osc2.start(ctx.currentTime)
    osc2.stop(ctx.currentTime + 0.12)
  } catch (e) {}
}

export function playWallBump() {
  try {
    const ctx = getCtx()
    const osc = ctx.createOscillator()
    const gain = ctx.createGain()
    const filter = ctx.createBiquadFilter()
    filter.type = 'lowpass'
    filter.frequency.value = 150
    osc.connect(filter)
    filter.connect(gain)
    gain.connect(ctx.destination)
    osc.type = 'triangle'
    osc.frequency.setValueAtTime(100 * (0.8 + Math.random() * 0.4), ctx.currentTime)
    gain.gain.setValueAtTime(0.05, ctx.currentTime)
    gain.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + 0.06)
    osc.start(ctx.currentTime)
    osc.stop(ctx.currentTime + 0.06)
  } catch (e) {}
}

// ============ Royal Road Music in A Minor ============

let musicGain = null
let musicActive = false
let musicTimeoutIds = []

export function startMusic() {
  try {
    const ctx = getCtx()
    stopMusic()
    musicActive = true

    musicGain = ctx.createGain()
    musicGain.gain.setValueAtTime(0.025, ctx.currentTime)
    musicGain.connect(ctx.destination)

    function scheduleLoop() {
      if (!musicActive || !musicGain) return
      scheduleProgression()
      // Schedule next loop after the full progression
      const tid = setTimeout(scheduleLoop, TOTAL_PROGRESSION_TIME * 1000)
      musicTimeoutIds.push(tid)
    }

    function scheduleProgression() {
      const now = ctx.currentTime

      // Play each chord
      for (let ci = 0; ci < 4; ci++) {
        const chordStart = now + ci * CHORD_DURATION
        const chordFreqs = CHORD_FREQS[ci]

        // Chord pads (soft, sustained)
        chordFreqs.forEach((freq, ni) => {
          const osc = ctx.createOscillator()
          const g = ctx.createGain()
          osc.connect(g)
          g.connect(musicGain)
          osc.type = ni === 0 ? 'sine' : 'triangle'
          osc.frequency.setValueAtTime(freq, chordStart)
          g.gain.setValueAtTime(0.06 / chordFreqs.length, chordStart)
          g.gain.linearRampToValueAtTime(0, chordStart + CHORD_DURATION - 0.1)
          osc.start(chordStart)
          osc.stop(chordStart + CHORD_DURATION)
          osc.onended = () => { try { osc.disconnect(); g.disconnect() } catch(e) {} }
        })

        // Bass note
        const bassOsc = ctx.createOscillator()
        const bassGain = ctx.createGain()
        bassOsc.connect(bassGain)
        bassGain.connect(musicGain)
        bassOsc.type = 'sine'
        bassOsc.frequency.setValueAtTime(BASS_FREQS[ci], chordStart)
        bassGain.gain.setValueAtTime(0.1, chordStart)
        bassGain.gain.linearRampToValueAtTime(0, chordStart + CHORD_DURATION - 0.1)
        bassOsc.start(chordStart)
        bassOsc.stop(chordStart + CHORD_DURATION)
        bassOsc.onended = () => { try { bassOsc.disconnect(); bassGain.disconnect() } catch(e) {} }

        // Melody arpeggio
        const melodyNotes = MELODY_FREQS[ci]
        melodyNotes.forEach((freq, mi) => {
          const noteStart = chordStart + mi * MELODY_NOTE_DURATION
          const osc = ctx.createOscillator()
          const g = ctx.createGain()
          osc.connect(g)
          g.connect(musicGain)
          osc.type = 'sine'
          osc.frequency.setValueAtTime(freq, noteStart)
          g.gain.setValueAtTime(0.07, noteStart)
          g.gain.exponentialRampToValueAtTime(0.001, noteStart + MELODY_NOTE_DURATION)
          osc.start(noteStart)
          osc.stop(noteStart + MELODY_NOTE_DURATION)
          osc.onended = () => { try { osc.disconnect(); g.disconnect() } catch(e) {} }
        })
      }
    }

    scheduleLoop()
  } catch (e) {}
}

export function stopMusic() {
  musicActive = false
  musicTimeoutIds.forEach((tid) => clearTimeout(tid))
  musicTimeoutIds = []
  if (musicGain) {
    try {
      musicGain.gain.exponentialRampToValueAtTime(0.001, getCtx().currentTime + 0.5)
    } catch (e) {}
    musicGain = null
  }
}
