// Procedural sound system using Web Audio API
// No external files needed — all sounds synthesized

// Royal Road progression in A minor — generated by python/generate_music.py
// Progression: Fmaj7 → G7 → Em7 → Am

const CHORD_FREQS = [
  /* Fmaj7 */ [349.23, 440.00, 523.25, 659.25],
  /* G7    */ [392.00, 493.88, 587.33, 698.46],
  /* Em7   */ [329.63, 392.00, 493.88, 587.33],
  /* Am    */ [220.00, 261.63, 329.63, 440.00],
];

const MELODY_FREQS = [
  /* Fmaj7 */ [349.23, 440.00, 523.25, 659.25, 523.25, 440.00],
  /* G7    */ [392.00, 493.88, 587.33, 698.46, 587.33, 493.88],
  /* Em7   */ [329.63, 392.00, 493.88, 587.33, 493.88, 392.00],
  /* Am    */ [220.00, 261.63, 329.63, 440.00, 329.63, 261.63],
];

const BASS_FREQS = [
  /* Fmaj7 */ 174.61,
  /* G7    */ 196.00,
  /* Em7   */ 164.81,
  /* Am    */ 110.00,
];

const CHORD_DURATION = 2.5;
const MELODY_NOTE_DURATION = 0.35;
const TOTAL_PROGRESSION_TIME = 10.0;

// ============ Audio context ============

let audioCtx = null

function getCtx() {
  if (!audioCtx) {
    audioCtx = new (window.AudioContext || window.webkitAudioContext)()
  }
  if (audioCtx.state === 'suspended') audioCtx.resume()
  return audioCtx
}

// ============ SFX ============

export function playFootstep() {
  try {
    const ctx = getCtx()
    const osc = ctx.createOscillator()
    const gain = ctx.createGain()
    // Low-pass filter for muffled stone step
    const filter = ctx.createBiquadFilter()
    filter.type = 'lowpass'
    filter.frequency.value = 400 + Math.random() * 200
    osc.connect(filter)
    filter.connect(gain)
    gain.connect(ctx.destination)
    osc.type = 'triangle'
    osc.frequency.setValueAtTime(60 + Math.random() * 40, ctx.currentTime)
    gain.gain.setValueAtTime(0.04, ctx.currentTime)
    gain.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + 0.1)
    osc.start(ctx.currentTime)
    osc.stop(ctx.currentTime + 0.1)
  } catch (e) { /* audio not available */ }
}

export function playCrystalCollect() {
  try {
    const ctx = getCtx()
    // Main chime
    const osc = ctx.createOscillator()
    const gain = ctx.createGain()
    osc.connect(gain)
    gain.connect(ctx.destination)
    osc.type = 'sine'
    osc.frequency.setValueAtTime(880, ctx.currentTime)
    osc.frequency.exponentialRampToValueAtTime(1760, ctx.currentTime + 0.15)
    gain.gain.setValueAtTime(0.12, ctx.currentTime)
    gain.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + 0.3)
    osc.start(ctx.currentTime)
    osc.stop(ctx.currentTime + 0.3)
    // Sparkle overtone
    const osc2 = ctx.createOscillator()
    const gain2 = ctx.createGain()
    osc2.connect(gain2)
    gain2.connect(ctx.destination)
    osc2.type = 'sine'
    osc2.frequency.setValueAtTime(1320, ctx.currentTime + 0.05)
    osc2.frequency.exponentialRampToValueAtTime(2640, ctx.currentTime + 0.2)
    gain2.gain.setValueAtTime(0.06, ctx.currentTime + 0.05)
    gain2.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + 0.25)
    osc2.start(ctx.currentTime + 0.05)
    osc2.stop(ctx.currentTime + 0.25)
  } catch (e) {}
}

export function playPortalActivate() {
  try {
    const ctx = getCtx()
    const osc = ctx.createOscillator()
    const gain = ctx.createGain()
    osc.connect(gain)
    gain.connect(ctx.destination)
    osc.type = 'triangle'
    osc.frequency.setValueAtTime(440, ctx.currentTime)
    osc.frequency.exponentialRampToValueAtTime(880, ctx.currentTime + 0.5)
    osc.frequency.exponentialRampToValueAtTime(1320, ctx.currentTime + 1.0)
    gain.gain.setValueAtTime(0.1, ctx.currentTime)
    gain.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + 1.2)
    osc.start(ctx.currentTime)
    osc.stop(ctx.currentTime + 1.2)
    // Hum layer
    const osc2 = ctx.createOscillator()
    const gain2 = ctx.createGain()
    osc2.connect(gain2)
    gain2.connect(ctx.destination)
    osc2.type = 'sine'
    osc2.frequency.setValueAtTime(220, ctx.currentTime)
    osc2.frequency.exponentialRampToValueAtTime(440, ctx.currentTime + 1.0)
    gain2.gain.setValueAtTime(0.05, ctx.currentTime)
    gain2.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + 1.2)
    osc2.start(ctx.currentTime)
    osc2.stop(ctx.currentTime + 1.2)
  } catch (e) {}
}

export function playDeath() {
  try {
    const ctx = getCtx()
    const osc = ctx.createOscillator()
    const gain = ctx.createGain()
    const osc2 = ctx.createOscillator()
    const gain2 = ctx.createGain()

    osc.connect(gain)
    gain.connect(ctx.destination)
    osc.type = 'sawtooth'
    osc.frequency.setValueAtTime(200, ctx.currentTime)
    osc.frequency.exponentialRampToValueAtTime(40, ctx.currentTime + 1.5)
    gain.gain.setValueAtTime(0.08, ctx.currentTime)
    gain.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + 1.8)

    osc2.connect(gain2)
    gain2.connect(ctx.destination)
    osc2.type = 'square'
    osc2.frequency.setValueAtTime(100, ctx.currentTime)
    osc2.frequency.exponentialRampToValueAtTime(20, ctx.currentTime + 1.5)
    gain2.gain.setValueAtTime(0.04, ctx.currentTime)
    gain2.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + 1.8)

    osc.start(ctx.currentTime)
    osc.stop(ctx.currentTime + 1.8)
    osc2.start(ctx.currentTime)
    osc2.stop(ctx.currentTime + 1.8)
  } catch (e) {}
}

export function playKeyCollect() {
  try {
    const ctx = getCtx()
    // Rising triplet
    const osc = ctx.createOscillator()
    const gain = ctx.createGain()
    osc.connect(gain)
    gain.connect(ctx.destination)
    osc.type = 'triangle'
    osc.frequency.setValueAtTime(660, ctx.currentTime)
    osc.frequency.setValueAtTime(880, ctx.currentTime + 0.1)
    osc.frequency.setValueAtTime(1100, ctx.currentTime + 0.2)
    gain.gain.setValueAtTime(0.1, ctx.currentTime)
    gain.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + 0.35)
    osc.start(ctx.currentTime)
    osc.stop(ctx.currentTime + 0.35)
    // Metallic ring
    const osc2 = ctx.createOscillator()
    const gain2 = ctx.createGain()
    osc2.connect(gain2)
    gain2.connect(ctx.destination)
    osc2.type = 'sine'
    osc2.frequency.setValueAtTime(2200, ctx.currentTime + 0.15)
    osc2.frequency.exponentialRampToValueAtTime(1800, ctx.currentTime + 0.4)
    gain2.gain.setValueAtTime(0.05, ctx.currentTime + 0.15)
    gain2.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + 0.45)
    osc2.start(ctx.currentTime + 0.15)
    osc2.stop(ctx.currentTime + 0.45)
  } catch (e) {}
}

export function playDoorOpen() {
  try {
    const ctx = getCtx()
    // Rumble + grind
    const osc = ctx.createOscillator()
    const gain = ctx.createGain()
    const filter = ctx.createBiquadFilter()
    filter.type = 'lowpass'
    filter.frequency.setValueAtTime(300, ctx.currentTime)
    filter.frequency.exponentialRampToValueAtTime(60, ctx.currentTime + 0.6)
    osc.connect(filter)
    filter.connect(gain)
    gain.connect(ctx.destination)
    osc.type = 'square'
    osc.frequency.setValueAtTime(180, ctx.currentTime)
    osc.frequency.exponentialRampToValueAtTime(60, ctx.currentTime + 0.6)
    gain.gain.setValueAtTime(0.08, ctx.currentTime)
    gain.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + 0.7)
    osc.start(ctx.currentTime)
    osc.stop(ctx.currentTime + 0.7)
    // Stone scrape overtone
    const osc2 = ctx.createOscillator()
    const gain2 = ctx.createGain()
    osc2.connect(gain2)
    gain2.connect(ctx.destination)
    osc2.type = 'sawtooth'
    osc2.frequency.setValueAtTime(80, ctx.currentTime)
    osc2.frequency.exponentialRampToValueAtTime(40, ctx.currentTime + 0.5)
    gain2.gain.setValueAtTime(0.03, ctx.currentTime)
    gain2.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + 0.6)
    osc2.start(ctx.currentTime)
    osc2.stop(ctx.currentTime + 0.6)
  } catch (e) {}
}

export function playSpikeHurt() {
  try {
    const ctx = getCtx()
    // Metallic sting — sharp and painful
    const osc = ctx.createOscillator()
    const gain = ctx.createGain()
    const filter = ctx.createBiquadFilter()
    filter.type = 'bandpass'
    filter.frequency.value = 3000
    filter.Q.value = 5
    osc.connect(filter)
    filter.connect(gain)
    gain.connect(ctx.destination)
    osc.type = 'square'
    osc.frequency.setValueAtTime(1200, ctx.currentTime)
    osc.frequency.exponentialRampToValueAtTime(400, ctx.currentTime + 0.15)
    gain.gain.setValueAtTime(0.1, ctx.currentTime)
    gain.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + 0.2)
    osc.start(ctx.currentTime)
    osc.stop(ctx.currentTime + 0.2)
    // Sub-harmonic thud
    const osc2 = ctx.createOscillator()
    const gain2 = ctx.createGain()
    osc2.connect(gain2)
    gain2.connect(ctx.destination)
    osc2.type = 'sine'
    osc2.frequency.setValueAtTime(55, ctx.currentTime)
    gain2.gain.setValueAtTime(0.06, ctx.currentTime)
    gain2.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + 0.12)
    osc2.start(ctx.currentTime)
    osc2.stop(ctx.currentTime + 0.12)
  } catch (e) {}
}

export function playWallBump() {
  try {
    const ctx = getCtx()
    const osc = ctx.createOscillator()
    const gain = ctx.createGain()
    const filter = ctx.createBiquadFilter()
    filter.type = 'lowpass'
    filter.frequency.value = 150
    osc.connect(filter)
    filter.connect(gain)
    gain.connect(ctx.destination)
    osc.type = 'triangle'
    osc.frequency.setValueAtTime(100 * (0.8 + Math.random() * 0.4), ctx.currentTime)
    gain.gain.setValueAtTime(0.05, ctx.currentTime)
    gain.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + 0.06)
    osc.start(ctx.currentTime)
    osc.stop(ctx.currentTime + 0.06)
  } catch (e) {}
}

// ============ Royal Road Music in A Minor ============

let musicGain = null
let musicActive = false
let musicTimeoutIds = []

export function startMusic() {
  try {
    const ctx = getCtx()
    stopMusic()
    musicActive = true

    musicGain = ctx.createGain()
    musicGain.gain.setValueAtTime(0.025, ctx.currentTime)
    musicGain.connect(ctx.destination)

    function scheduleLoop() {
      if (!musicActive || !musicGain) return
      scheduleProgression()
      // Schedule next loop after the full progression
      const tid = setTimeout(scheduleLoop, TOTAL_PROGRESSION_TIME * 1000)
      musicTimeoutIds.push(tid)
    }

    function scheduleProgression() {
      const now = ctx.currentTime

      // Play each chord
      for (let ci = 0; ci < 4; ci++) {
        const chordStart = now + ci * CHORD_DURATION
        const chordFreqs = CHORD_FREQS[ci]

        // Chord pads (soft, sustained)
        chordFreqs.forEach((freq, ni) => {
          const osc = ctx.createOscillator()
          const g = ctx.createGain()
          osc.connect(g)
          g.connect(musicGain)
          osc.type = ni === 0 ? 'sine' : 'triangle'
          osc.frequency.setValueAtTime(freq, chordStart)
          g.gain.setValueAtTime(0.06 / chordFreqs.length, chordStart)
          g.gain.linearRampToValueAtTime(0, chordStart + CHORD_DURATION - 0.1)
          osc.start(chordStart)
          osc.stop(chordStart + CHORD_DURATION)
          osc.onended = () => { try { osc.disconnect(); g.disconnect() } catch(e) {} }
        })

        // Bass note
        const bassOsc = ctx.createOscillator()
        const bassGain = ctx.createGain()
        bassOsc.connect(bassGain)
        bassGain.connect(musicGain)
        bassOsc.type = 'sine'
        bassOsc.frequency.setValueAtTime(BASS_FREQS[ci], chordStart)
        bassGain.gain.setValueAtTime(0.1, chordStart)
        bassGain.gain.linearRampToValueAtTime(0, chordStart + CHORD_DURATION - 0.1)
        bassOsc.start(chordStart)
        bassOsc.stop(chordStart + CHORD_DURATION)
        bassOsc.onended = () => { try { bassOsc.disconnect(); bassGain.disconnect() } catch(e) {} }

        // Melody arpeggio
        const melodyNotes = MELODY_FREQS[ci]
        melodyNotes.forEach((freq, mi) => {
          const noteStart = chordStart + mi * MELODY_NOTE_DURATION
          const osc = ctx.createOscillator()
          const g = ctx.createGain()
          osc.connect(g)
          g.connect(musicGain)
          osc.type = 'sine'
          osc.frequency.setValueAtTime(freq, noteStart)
          g.gain.setValueAtTime(0.07, noteStart)
          g.gain.exponentialRampToValueAtTime(0.001, noteStart + MELODY_NOTE_DURATION)
          osc.start(noteStart)
          osc.stop(noteStart + MELODY_NOTE_DURATION)
          osc.onended = () => { try { osc.disconnect(); g.disconnect() } catch(e) {} }
        })
      }
    }

    scheduleLoop()
  } catch (e) {}
}

export function stopMusic() {
  musicActive = false
  musicTimeoutIds.forEach((tid) => clearTimeout(tid))
  musicTimeoutIds = []
  if (musicGain) {
    try {
      musicGain.gain.exponentialRampToValueAtTime(0.001, getCtx().currentTime + 0.5)
    } catch (e) {}
    musicGain = null
  }
}

export function setMusicVolume(vol) {
  if (musicGain) {
    try {
      musicGain.gain.setValueAtTime(vol * 0.025, getCtx().currentTime)
    } catch (e) {}
  }
}

// ============ Ambient Cave Sounds ============

let ambientGain = null
let ambientActive = false
let ambientTimeoutIds = []
let ambientDripIds = []

export function startAmbient() {
  try {
    const ctx = getCtx()
    stopAmbient()
    ambientActive = true

    ambientGain = ctx.createGain()
    ambientGain.gain.setValueAtTime(0.03, ctx.currentTime)
    ambientGain.connect(ctx.destination)

    // ---- Low wind/draft drone ----
    function createDrone() {
      if (!ambientActive || !ambientGain) return
      const now = ctx.currentTime

      // Use filtered noise for wind
      const bufferSize = ctx.sampleRate * 2
      const buffer = ctx.createBuffer(1, bufferSize, ctx.sampleRate)
      const data = buffer.getChannelData(0)
      // Brown noise (heavy low-end rumble)
      let lastOut = 0
      for (let i = 0; i < bufferSize; i++) {
        const white = Math.random() * 2 - 1
        lastOut = (lastOut + 0.02 * white) / 1.02
        data[i] = lastOut * 3
      }

      const noise = ctx.createBufferSource()
      noise.buffer = buffer
      noise.loop = true

      const bandpass = ctx.createBiquadFilter()
      bandpass.type = 'bandpass'
      bandpass.frequency.value = 120 + Math.random() * 80
      bandpass.Q.value = 0.3

      const lowpass = ctx.createBiquadFilter()
      lowpass.type = 'lowpass'
      lowpass.frequency.value = 200

      const g = ctx.createGain()
      g.gain.value = 0.15 + Math.random() * 0.1
      // Subtle volume wobble
      const lfo = ctx.createOscillator()
      const lfoGain = ctx.createGain()
      lfo.frequency.value = 0.05 + Math.random() * 0.1
      lfoGain.gain.value = 0.04
      lfo.connect(lfoGain)
      lfoGain.connect(g.gain)
      lfo.start(now)
      lfo.stop(now + 30)

      noise.connect(bandpass)
      bandpass.connect(lowpass)
      lowpass.connect(g)
      g.connect(ambientGain)
      noise.start(now)
      noise.stop(now + 30)

      noise.onended = () => {
        try { noise.disconnect(); bandpass.disconnect(); lowpass.disconnect(); g.disconnect(); lfo.disconnect(); lfoGain.disconnect() } catch(e) {}
      }

      // Respawn drone with different params
      const tid = setTimeout(createDrone, 25000 + Math.random() * 10000)
      ambientTimeoutIds.push(tid)
    }

    // ---- Water drips ----
    function scheduleDrips() {
      if (!ambientActive || !ambientGain) return
      const now = ctx.currentTime

      // Schedule several drips at random intervals
      const numDrips = 4 + Math.floor(Math.random() * 5)
      for (let i = 0; i < numDrips; i++) {
        const dripTime = now + Math.random() * 12
        const osc = ctx.createOscillator()
        const g = ctx.createGain()

        // Echo chain — a simple delay/reverb simulation
        const delay = ctx.createDelay(0.3)
        delay.delayTime.value = 0.15 + Math.random() * 0.2
        const feedback = ctx.createGain()
        feedback.gain.value = 0.2

        const highpass = ctx.createBiquadFilter()
        highpass.type = 'highpass'
        highpass.frequency.value = 800

        osc.connect(g)
        g.connect(highpass)
        highpass.connect(ambientGain)
        // Feedback loop for echo
        highpass.connect(delay)
        delay.connect(feedback)
        feedback.connect(highpass)

        osc.type = 'sine'
        osc.frequency.setValueAtTime(1200 + Math.random() * 800, dripTime)
        osc.frequency.exponentialRampToValueAtTime(400 + Math.random() * 300, dripTime + 0.15)
        g.gain.setValueAtTime(0.0001, dripTime)
        g.gain.exponentialRampToValueAtTime(0.12 + Math.random() * 0.08, dripTime + 0.01)
        g.gain.exponentialRampToValueAtTime(0.001, dripTime + 0.3)
        osc.start(dripTime)
        osc.stop(dripTime + 0.35)

        const id = { osc, g, delay, feedback, highpass }
        ambientDripIds.push(id)
        osc.onended = () => {
          try { osc.disconnect(); g.disconnect(); delay.disconnect(); feedback.disconnect(); highpass.disconnect() } catch(e) {}
          const idx = ambientDripIds.indexOf(id)
          if (idx !== -1) ambientDripIds.splice(idx, 1)
        }
      }

      const tid = setTimeout(scheduleDrips, 10000 + Math.random() * 5000)
      ambientTimeoutIds.push(tid)
    }

    // ---- Distant rumble/stone settling ----
    function scheduleRumbles() {
      if (!ambientActive || !ambientGain) return
      const now = ctx.currentTime

      const rumbleTime = now + Math.random() * 15
      const osc = ctx.createOscillator()
      const g = ctx.createGain()
      const lowpass = ctx.createBiquadFilter()
      lowpass.type = 'lowpass'
      lowpass.frequency.value = 40 + Math.random() * 30

      osc.connect(lowpass)
      lowpass.connect(g)
      g.connect(ambientGain)

      osc.type = 'sine'
      osc.frequency.setValueAtTime(20 + Math.random() * 25, rumbleTime)
      g.gain.setValueAtTime(0.0001, rumbleTime)
      g.gain.exponentialRampToValueAtTime(0.06 + Math.random() * 0.04, rumbleTime + 0.3)
      g.gain.exponentialRampToValueAtTime(0.001, rumbleTime + 2.0 + Math.random() * 1.5)
      osc.start(rumbleTime)
      osc.stop(rumbleTime + 2.5 + Math.random() * 2)

      osc.onended = () => { try { osc.disconnect(); lowpass.disconnect(); g.disconnect() } catch(e) {} }

      const tid = setTimeout(scheduleRumbles, 12000 + Math.random() * 18000)
      ambientTimeoutIds.push(tid)
    }

    createDrone()
    scheduleDrips()
    scheduleRumbles()
  } catch (e) {}
}

export function stopAmbient() {
  ambientActive = false
  ambientTimeoutIds.forEach((tid) => clearTimeout(tid))
  ambientTimeoutIds = []
  // Kill lingering drip nodes
  ambientDripIds.forEach(({ osc, g, delay, feedback, highpass }) => {
    try { osc.stop(); osc.disconnect() } catch(e) {}
    try { g.disconnect() } catch(e) {}
    try { delay.disconnect() } catch(e) {}
    try { feedback.disconnect() } catch(e) {}
    try { highpass.disconnect() } catch(e) {}
  })
  ambientDripIds = []
  if (ambientGain) {
    try {
      ambientGain.gain.exponentialRampToValueAtTime(0.001, getCtx().currentTime + 0.3)
    } catch (e) {}
    ambientGain = null
  }
}

export function setAmbientVolume(vol) {
  if (ambientGain) {
    try {
      ambientGain.gain.setValueAtTime(vol * 0.03, getCtx().currentTime)
    } catch (e) {}
  }
}
