"""
Generate the Royal Road chord progression in A minor for a dungeon crawler game.
Royal Road (王道進行): IVmaj7 → V7 → iii7 → vi
In A minor: Fmaj7 → G7 → Em7 → Am

Outputs a JavaScript array of note objects ready for Web Audio API.
Each note has [frequency, startTime_offset, duration] for the melody line.
"""

import json
import math

# A minor scale frequencies (A2 to A5)
A_MINOR_SCALE = {
    'A2': 110.00, 'B2': 123.47, 'C3': 130.81, 'D3': 146.83,
    'E3': 164.81, 'F3': 174.61, 'G3': 196.00, 'A3': 220.00,
    'B3': 246.94, 'C4': 261.63, 'D4': 293.66, 'E4': 329.63,
    'F4': 349.23, 'G4': 392.00, 'A4': 440.00,
    'B4': 493.88, 'C5': 523.25, 'D5': 587.33, 'E5': 659.25,
    'F5': 698.46, 'G5': 783.99, 'A5': 880.00,
}

# Chord definitions (root + intervals)
def chord(notes, octave_offset=0):
    """Return frequencies for chord notes"""
    result = []
    for n in notes:
        base = n[:-1]  # e.g., 'A' from 'A4'
        octave = int(n[-1]) + octave_offset
        key = f"{base}{octave}"
        if key in A_MINOR_SCALE:
            result.append(A_MINOR_SCALE[key])
    return result

# Royal Road progression in A minor:
# Fmaj7 → G7 → Em7 → Am
# Fmaj7: F, A, C, E  →  F4, A4, C5, E5
# G7:    G, B, D, F   →  G4, B4, D5, F5
# Em7:   E, G, B, D   →  E4, G4, B4, D5
# Am:    A, C, E, A   →  A3, C4, E4, A4

PROGRESSION = [
    {'name': 'Fmaj7', 'notes': ['F4', 'A4', 'C5', 'E5']},
    {'name': 'G7',    'notes': ['G4', 'B4', 'D5', 'F5']},
    {'name': 'Em7',   'notes': ['E4', 'G4', 'B4', 'D5']},
    {'name': 'Am',    'notes': ['A3', 'C4', 'E4', 'A4']},
]

# Melody notes (arpeggiated from each chord)
MELODY_PATTERNS = [
    # Fmaj7 arpeggio
    ['F4', 'A4', 'C5', 'E5', 'C5', 'A4'],
    # G7 arpeggio
    ['G4', 'B4', 'D5', 'F5', 'D5', 'B4'],
    # Em7 arpeggio
    ['E4', 'G4', 'B4', 'D5', 'B4', 'G4'],
    # Am arpeggio
    ['A3', 'C4', 'E4', 'A4', 'E4', 'C4'],
]

# Bass line (root notes, one octave down from chord root)
BASS_LINE = ['F3', 'G3', 'E3', 'A2']

# Generate JS output
def gen_js():
    lines = []
    lines.append('// Royal Road progression in A minor — generated by python/generate_music.py')
    lines.append('// Progression: Fmaj7 → G7 → Em7 → Am')
    lines.append('')
    
    # Chord frequencies
    lines.append('const CHORD_FREQS = [')
    for i, chord_data in enumerate(PROGRESSION):
        freqs = [A_MINOR_SCALE[n] for n in chord_data['notes'] if n in A_MINOR_SCALE]
        lines.append(f'  /* {chord_data["name"]} */ [{", ".join(f"{f:.2f}" for f in freqs)}],')
    lines.append('];')
    lines.append('')
    
    # Melody frequencies
    lines.append('const MELODY_FREQS = [')
    for i, notes in enumerate(MELODY_PATTERNS):
        freqs = [A_MINOR_SCALE[n] for n in notes if n in A_MINOR_SCALE]
        lines.append(f'  /* {PROGRESSION[i]["name"]} */ [{", ".join(f"{f:.2f}" for f in freqs)}],')
    lines.append('];')
    lines.append('')
    
    # Bass frequencies
    lines.append('const BASS_FREQS = [')
    for i, note in enumerate(BASS_LINE):
        freq = A_MINOR_SCALE.get(note, 0)
        lines.append(f'  /* {PROGRESSION[i]["name"]} */ {freq:.2f},')
    lines.append('];')
    lines.append('')
    
    # Chord duration per chord (in seconds)
    lines.append(f'const CHORD_DURATION = {2.5};  // seconds per chord')
    lines.append(f'const MELODY_NOTE_DURATION = {0.35};  // seconds per melody note')
    lines.append(f'const TOTAL_PROGRESSION_TIME = {4 * 2.5};  // 4 chords × 2.5s = 10s loop')
    lines.append('')
    
    # Export for sound.js
    lines.append('export { CHORD_FREQS, MELODY_FREQS, BASS_FREQS, CHORD_DURATION, MELODY_NOTE_DURATION, TOTAL_PROGRESSION_TIME };')
    
    return '\n'.join(lines)


def gen_json():
    """Also output as JSON for reference"""
    data = {
        'key': 'A minor',
        'progression': 'Fmaj7 → G7 → Em7 → Am (Royal Road)',
        'chord_duration_s': 2.5,
        'total_loop_s': 10.0,
        'chords': PROGRESSION,
        'melody': MELODY_PATTERNS,
        'bass': BASS_LINE,
    }
    return json.dumps(data, indent=2)


if __name__ == '__main__':
    print("// ===== JS OUTPUT (copy to sound.js music section) =====")
    print(gen_js())
    print()
    print("// ===== JSON REFERENCE =====")
    print(gen_json())
